language: java
jdk: openjdk8

env:
  global:
    # dirs
    - ANDROID_SDK_DIR: "android-sdk"
    - GRADLE_DIR: ".gradle"
    # links
    - ANDROID_SDK_LINK: "https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip"

before_install:
  - if [[ ! -d ${ANDROID_SDK_DIR} ]] ; then wget -q -O android-sdk.zip ${ANDROID_SDK_LINK} ; fi
  - if [[ ! -d ${ANDROID_SDK_DIR} ]] ; then unzip -d ${ANDROID_SDK_DIR} android-sdk.zip > /dev/null ; fi
  # setting environmental variables
  - export ANDROID_SDK_ROOT=$PWD/${ANDROID_SDK_DIR}
  - export GRADLE_USER_HOME=$PWD/${GRADLE_DIR}
  # Workaround for "Warning: Could not create settings"
  - echo y | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "tools" > /dev/null
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses > /dev/null
  - set -o pipefail

install:
  - ./gradlew init

script:
  - ./gradlew detekt lintDebug testDebugUnitTest assembleDebug
