language: android
jdk: oraclejdk8

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools

script:
  - ./gradlew detekt lint assembleDebug