plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("kapt")

    id("com.github.triplet.play") version "3.7.0"
    id("ru.erdenian.shrinkometer")
}

android {
    namespace = "com.erdenian.studentassistant"

    defaultConfig {
        applicationId = "com.erdenian.studentassistant"
        versionCode = 20
        versionName = "0.5.1"

        setProperty("archivesBaseName", "${rootProject.name}-$versionName")
    }

    lint {
        checkDependencies = true
        checkAllWarnings = true
        xmlReport = false
        checkTestSources = true
    }

    buildFeatures.compose = true

    signingConfigs {
        val localProperties = File("${rootDir.path}/local.properties").run {
            if (exists()) `java.util`.Properties().apply { load(inputStream()) } else null
        }
        val environment = System.getenv()
        fun get(env: String, local: String) = environment[env] ?: run {
            project.logger.info("No $env environmental variable")
            localProperties?.getProperty(local) ?: run {
                project.logger.info("No $local local property")
                null
            }
        }

        data class Keystore(
            val storeFile: File,
            val storePassword: String,
            val keyAlias: String,
            val keyPassword: String
        )

        fun getReleaseKeystore(): Keystore? {
            return Keystore(
                rootProject.file("signing/release.jks"),
                get("ANDROID_KEYSTORE_PASSWORD", "signing.keystorePassword") ?: return null,
                get("ANDROID_KEY_ALIAS", "signing.keyAlias") ?: return null,
                get("ANDROID_KEY_PASSWORD", "signing.keyPassword") ?: return null
            )
        }

        getByName("debug") {
            storeFile = rootProject.file("signing/debug.jks")
            storePassword = "debugdebug"
            keyAlias = "debug"
            keyPassword = "debugdebug"

            enableV1Signing = true
            enableV2Signing = true
            enableV3Signing = true
            enableV4Signing = true
        }

        getReleaseKeystore()?.let { keystore ->
            create("release") {
                storeFile = keystore.storeFile
                storePassword = keystore.storePassword
                keyAlias = keystore.keyAlias
                keyPassword = keystore.keyPassword

                enableV1Signing = true
                enableV2Signing = true
                enableV3Signing = true
                enableV4Signing = true
            }
        } ?: project.logger.warn("WARNING: Can't create release signing config")
    }

    buildTypes {
        getByName("debug") {
            signingConfig = signingConfigs.getByName("debug")
        }
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.findByName("release")
        }
    }
}

dependencies {
    // region Private
    implementation(project(":core:style"))
    implementation(project(":core:strings"))

    implementation(project(":data:repository"))

    implementation(project(":features:schedule"))
    implementation(project(":features:homeworks"))
    implementation(project(":features:settings"))
    // endregion

    // region AndroidX
    val appcompatVersion: String by project
    implementation("androidx.appcompat:appcompat:$appcompatVersion")
    val activityVersion: String by project
    implementation("androidx.activity:activity-compose:$activityVersion")
    val navigationVersion: String by project
    implementation("androidx.navigation:navigation-compose:$navigationVersion")
    val splashscreenVersion: String by project
    implementation("androidx.core:core-splashscreen:$splashscreenVersion")
    // endregion

    // region Core
    val daggerVersion: String by project
    implementation("com.google.dagger:dagger:$daggerVersion")
    kapt("com.google.dagger:dagger-compiler:$daggerVersion")

    // Required in code generated by Dagger
    compileOnly(project(":data:database"))
    val roomVersion: String by project
    compileOnly("androidx.room:room-ktx:$roomVersion")
    // endregion

    // region UI
    val accompanistVersion: String by project
    implementation("com.google.accompanist:accompanist-navigation-animation:$accompanistVersion")

    val materialVersion: String by project
    implementation("com.google.android.material:material:$materialVersion")
    // endregion
}

play {
    track.set("beta")
    releaseStatus.set(com.github.triplet.gradle.androidpublisher.ReleaseStatus.DRAFT)
    defaultToAppBundles.set(true)
}
