name: Commit

on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
      - 'release/*'

jobs:

  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Detekt
        run: ./gradlew detekt
