name: Commit

on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
      - 'release/*'

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      # --------------------------------------
      # Check
      # --------------------------------------
      - name: Detekt
        run: ./gradlew detekt
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Detekt
          path: "build/reports/detekt/detekt.html"
          if-no-files-found: error
