name: Commit

on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
      - 'release/*'

jobs:
  check:
    runs-on: self-hosted
    steps:
      # --------------------------------------
      # Install
      # --------------------------------------
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      # --------------------------------------
      # Run
      # --------------------------------------
      - uses: actions/checkout@v3
      - run: ./gradlew :detekt
      # --------------------------------------
      # Analyze
      # --------------------------------------
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Detekt
          path: "build/reports/detekt/detekt.html"
          if-no-files-found: error
