name: Commit

on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
      - 'release/*'

jobs:
  check:
    runs-on: self-hosted
    steps:
      # --------------------------------------
      # Install
      # --------------------------------------
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: android-actions/setup-android@v3
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          link-to-sdk: true
      - uses: gradle/actions/setup-gradle@v3
      # --------------------------------------
      # Run
      # --------------------------------------
      - uses: actions/checkout@v4
      - run: ./gradlew detektMain
      # --------------------------------------
      # Analyze
      # --------------------------------------
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Detekt
          path: "**/build/reports/detekt/detekt.html"
          if-no-files-found: error
