name: Develop

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

env:
  MIN_COVERAGE_OVERALL: 4
  MIN_COVERAGE_CHANGED: 0

jobs:
  check:
    runs-on: macos-latest
    steps:
      # --------------------------------------
      # Install
      # --------------------------------------
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      # --------------------------------------
      # Run
      # --------------------------------------
      - uses: actions/checkout@v3
      - run: ./gradlew :detekt :app:lintDebug testDebugUnitTest testDeviceDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" :jacocoMergedReport :app:assembleDebug :app:bundleDebug
      # --------------------------------------
      # Analyze
      # --------------------------------------
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Detekt
          path: "build/reports/detekt/detekt.html"
          if-no-files-found: error
      # --------------------------------------
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Lint
          path: "**/build/reports/lint-results*.html"
          if-no-files-found: error
      # --------------------------------------
      # Test
      # --------------------------------------
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Unit Test
          path: "**/build/reports/tests/"
          if-no-files-found: error
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Report
          path: "**/build/test-results/test*/TEST-*.xml"
          reporter: java-junit
      # --------------------------------------
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Android Test
          path: "**/build/reports/androidTests/"
          if-no-files-found: error
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Android Test Report
          path: "**/build/outputs/androidTest-results/managedDevice/testDevice/TEST-*.xml"
          reporter: java-junit
      # --------------------------------------
      - uses: madrapps/jacoco-report@v1.4
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: ${{ env.MIN_COVERAGE_OVERALL }}
          min-coverage-changed-files: ${{ env.MIN_COVERAGE_CHANGED }}
      # --------------------------------------
      # Build
      # --------------------------------------
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: Assemble
          path: "app/build/outputs/apk/debug/*.apk"
          if-no-files-found: error
      # --------------------------------------
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: Bundle
          path: "app/build/outputs/bundle/debug/*.aab"
          if-no-files-found: error
