name: Develop

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:

  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}-${{ github.job }}
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.gradle
            ${{ github.workspace }}/**/build
          key: ${{ github.sha }}-${{ github.job }}
          restore-keys: ${{ github.sha }}-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Detekt
        run: ./gradlew detekt
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Detekt
          path: "build/reports/detekt/detekt.html"
          if-no-files-found: error
      - name: Lint Debug
        run: ./gradlew lintDebug
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Lint
          path: "*/build/reports/lint-results*.html"
          if-no-files-found: error

  test:
    needs: analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}-${{ github.job }}
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.gradle
            ${{ github.workspace }}/**/build
          key: ${{ github.sha }}-${{ github.job }}
          restore-keys: ${{ github.sha }}-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Unit Test
          path: "*/build/reports/tests/"
          if-no-files-found: error

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}-${{ github.job }}
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.gradle
            ${{ github.workspace }}/**/build
          key: ${{ github.sha }}-${{ github.job }}
          restore-keys: ${{ github.sha }}-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Assemble Debug
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Assemble
          path: "app/build/outputs/apk/debug/*.apk"
          if-no-files-found: error
      - name: Bundle Debug
        run: ./gradlew bundleDebug
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Bundle
          path: "app/build/outputs/bundle/debug/*.aab"
          if-no-files-found: error
