name: Master

on:
  push:
    branches:
      - 'master'

jobs:

  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Detekt
        run: ./gradlew detekt
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Detekt
          path: build/reports/detekt/detekt.html
      - name: Lint Release
        run: ./gradlew lintRelease
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Lint
          path: "*/build/reports/lint-results*.html"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit Test
        run: ./gradlew testReleaseUnitTest
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Unit Test
          path: "*/build/reports/tests/"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Assemble Release
        run: ./gradlew assembleRelease
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Assemble
          path: app/build/outputs/apk/release/*.apk
      - name: Bundle Release
        run: ./gradlew bundleRelease
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Bundle
          path: app/build/outputs/bundle/release/*.aab
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Mappings
          path: app/build/outputs/mapping/release/*.txt

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish
        run: ./gradlew publishReleaseBundle
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
