name: Release

on:
  push:
    branches:
      - 'release/*'
  pull_request:
    branches:
      - 'master'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      # --------------------------------------
      # Check
      # --------------------------------------
      - name: Detekt
        run: ./gradlew detekt
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Detekt
          path: "build/reports/detekt/detekt.html"
          if-no-files-found: error
      # --------------------------------------
      - name: Lint Release
        run: ./gradlew :app:lintRelease
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Lint
          path: "**/build/reports/lint-results*.html"
          if-no-files-found: error
      # --------------------------------------
      # Test
      # --------------------------------------
      - name: Unit Test
        run: ./gradlew testReleaseUnitTest
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Unit Test
          path: "**/build/reports/tests/"
          if-no-files-found: error
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Report
          path: "**/build/test-results/test*/TEST-*.xml"
          reporter: java-junit
      # --------------------------------------
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Android Test
        run: ./gradlew testDeviceDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Android Test
          path: "**/build/reports/androidTests/"
          if-no-files-found: error
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Android Test Report
          path: "**/build/outputs/androidTest-results/managedDevice/testDevice/TEST-*.xml"
          reporter: java-junit
      # --------------------------------------
      # Build
      # --------------------------------------
      - name: Assemble Release
        run: ./gradlew assembleRelease
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: Assemble
          path:
            - "app/build/outputs/apk/release/*.apk"
            - "app/build/outputs/mapping/release/*.txt"
          if-no-files-found: error
      # --------------------------------------
      - name: Bundle Release
        run: ./gradlew bundleRelease
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: Bundle
          path:
            - "app/build/outputs/bundle/release/*.aab"
            - "app/build/outputs/mapping/release/*.txt"
          if-no-files-found: error
